### ISSUE TITLE
A quick question on Lexing (i.e., Section 2.1)

### ISSUE THREAD

**Issue by entslscheia** [ElementAI/picard#24]
Hi,

I have a clarification question regarding the Lexing part of PICARD.
First of all, I understand that the purpose of Lexing is to get rid of the invalid tokens (e.g., `cell_phone` in your paper) from the decoder's prediction. However, I am confused with how you generate tokens like `cell_phone` in the first place? Considering that `cell_phone` is not likely to be in T5's pertained vocab, what you would probably have are just `cell` and `phone`. So do you predict a single schema item `cell_phone` in multiple steps? Wouldn't it be nicer to predict these schema tokens in an atomic way (concretely, you will have a candidate which is `cell_number`, but you would not have `cell_phone` as your candidate at all)? That would save much computation on generating those invalid tokens. I might also misunderstand your method. Could you clarify this part a bit for me? Many thanks!

**Comment by tscholak** [comment]
Hi @entslscheia!

As you remarked yourself, there is a difference between model tokens and lexical tokens. T5's tokenizer will almost surely split up table/column names in awkward places, and this has to be taken into account.
Luckily, the solution is straightforward: One has to use the T5 tokenizer to decode the token indices to decode the string incrementally.

Suppose that T5 produces first `cell` and then `_`. At this point, everything is alright, because these two tokens combine to `cell_`, which is a correct (partial) column name. The next token makes all the difference, though. PICARD will reject `phone` and admit `number`.

I think you are referring to the above as "predicting a single schema item in multiple steps". This is indeed what's happening. The alternative you are suggesting may be possible in cases where there is only one correct way to continue a sequence of tokens. I am not sure how often that happens, though. If if this saved some model computation time, it may be too rare to make a difference.

**Comment by entslscheia** [comment]
Hi @tscholak !
Your answer perfectly addressed my concern! Have a good day!
