### ISSUE TITLE
How is the input sequence length determined?

### ISSUE THREAD

**Issue by atosystem** [ElementAI/picard#30]
Hi @tscholak !

I am wondering how you decide the maximum src_length and tgt_length. It seems that there are several input larger than the limit 512. Does this truncation deteriorate the performance? Since, truncation always occurs in  DB_Content and DB_Schema?

Thanks!

**Comment by tscholak** [comment]
Hi, we have looked at the statistics of input and target sequence lengths across the training and evaluation datasets, and decided that a maximum of 512 tokens is a good compromise between memory consumption and performance. For most databases in the Spider dataset, 512 is much more than enough. There are one or two large schemas with a very long linearization where truncation occurs, and for those performance is diminished Anaya at because the schema is too complex and the examples to sparse to have enough coverage for the model to figure the schemas out. For CoSQL, a higher maximum than 512 for the input length may be beneficial, because not only do we need to encode the question and schema, but also the previous questions on the dialogue. Those are appended in reverse chronological order at the end of the input, after the schema. Truncation happens more frequently on CoSQL, but we are able to reduce the detrimental effect of it due to the reverse chronological evaluation order. In most cases, relevant conversational context is found in immediately preceding questions. Even though T5 has been pretrained with a context width of 512, it can support longer inputs due to its relative and bucketed positional encoding. One therefore can experiment with larger maximum lengths, but we haven't done so due to computational limitations, mostly memory.

**Comment by atosystem** [comment]
Thanks a lot!
