### ISSUE TITLE
make init-buildkit

### ISSUE THREAD

**Issue by JessicaLopezEspejel** [ElementAI/picard#52]
Hello, 

Thank you for your work. I am working in a text2sql project, so I cloned your repo. 
I followed your instructions:

```
$ git clone git@github.com:ElementAI/picard.git
$ cd picard
$ git submodule update --init --recursive
```

Until here, it worked very well. Later, I executed: `make pull-eval-image` and also it worked.
However, when I executed `make init-buildkit`, it returned the following mistake. 

![picard_error](https://user-images.githubusercontent.com/53188008/152532952-27a06c05-3351-4e93-b14c-71cf9243559d.PNG)

My goal is to get the output file and reproduce your results to check the sql queries the model is generating. Besides, I would like to deploy your model.

Specifications: 

I am using the Ubuntu terminal in Windows.
I am only using CPU.

Thank you so much in advance.

**Comment by tscholak** [comment]
Hi @JessicaLopezEspejel!
Both of your goals should be achievable without running `make build-eval-image`. This command is reserved for maintainers only, because it will need to upload the produced image to a repository on the docker hub, which requires authorization.
I suggest you use `make eval` instead. This command will launch a docker container from the `eval` image (downloaded from https://hub.docker.com/r/tscholak/text-to-sql-eval), run the evaluation on the spider dataset using the eval configuration in the `config` folder. It will also save the predictions to a file in the `eval` folder that it will create.
For deployment, I have created the `make serve` target. This will launch a REST service that you can query on sqlite databases. There have been multiple questions about that already, please use search to find them.
Let me know if you have further questions.

**Comment by JessicaLopezEspejel** [comment]
Thank for very much for your reply.  However, I executed `make eval` in a linux system with 32 GB RAM, and I only use CPU. During 24hr it has an advancement of 52%, is it that normal? Besides, I know that PICARD works text-to-sql, but if I want to use it with java, do you have any suggestion?

**Comment by tscholak** [comment]
Hi,
The model runs slowly on CPU, but it will finish. With 16 cores, I think it took 5 hours to complete the evaluation when I last ran it.
Regarding Java, I don't have a solution for you. You could write a Java parser in the way I did it here for SQL. That would give you a good way to control precisely what subset and style of Java you want to support. In other cases, support for the full Java language can be achieved by using an existing BNF grammar file with a third-party parser framework. The authors of the Synchromesh paper did that recently with ANTLR. That's an accepted ICLR '22 submission, see openreview. I don't know if their code is already available, though.

**Comment by tscholak** [comment]
I hope evaluation has worked for you by now. I'm going to close this issue. Feel free to reopen if the issue persists.
