### ISSUE TITLE
Add Spider-realistic

### ISSUE THREAD

**Issue by tscholak** [ElementAI/picard#59]
See https://zenodo.org/record/5205322#.Ygpi3S-B0Xw

**Comment by kotalaraghava** [comment]
Hey @tscholak, I would like to take up this issue and contribute.


I suppose I need to add `spider_realistic.py at [picard/seq2seq/datasets/]` and 

some straight-forward code here:  `[picard/seq2seq/utils/dataset_loader.py]`

Since it is only used for evaluation I need to test it while calling the evaluation module only.

Is that it ? or any other changes?

Thanks,
Raghav

**Comment by tscholak** [comment]
Hi Raghav,
Yes, that sounds about right!
Looking forward to your contribution!

**Comment by tscholak** [comment]
support added by #69
