### ISSUE TITLE
Setting up PICARD without using the Docker images

### ISSUE THREAD

**Issue by rajaswa** [ElementAI/picard#6]
I have been attempting to run the evaluation script without using the docker image. I am facing an error which says: `picard is not available`. Is there any specific set of instructions for setting up picard without using the docker images?

**Comment by tscholak** [comment]
Hi @rajaswa,
Thank you for your interest in picard! The message you are seeing indicates that the picard backend is not fully installed. The Python code you ran covers only half of the implementation. You also need to run the picard executable. Normally, this is done automatically when you launch the script, but in your case I suspect it failed because of a bunch of missing dependencies in your environment -- most likely Thrift, https://github.com/facebook/fbthrift. So far, there is no writeup of these dependencies or how to build them. Your best bet at the moment is the https://github.com/ElementAI/picard/blob/main/Dockerfile. Everything that goes into the build is specified there, and you can run these lines yourself in your environment. However, since the toolchain is big and complex, I strongly recommend using the provided Docker images. If there is a concrete use case that prohibits you from using them, you can message me and tell me a bit more about what you are trying to do. Perhaps I can make it easier for you.
Best,
Torsten
