### ISSUE TITLE
How to generate SQL queries which supports MSSQL instead of SQLite

### ISSUE THREAD

**Issue by b4zyuvaraj** [ElementAI/picard#99]
Hi @tscholak

I want to execute the SQL queries in MSSQL instead of SQLite. Is there any possibilities or configuration changes which generates the MSSQL queries?

Thanks
Yuvaraj

**Comment by tscholak** [comment]
MSSQL is currently not supported. Numerous changes would be necessary to support MSSQL:

* The idioms and grammar of MSSQL would need to be added to the PICARD parser,
* The Spider databases and text-to-SQL data would need to be translated from SQLite to MSSQL,
* The models would need to be retrained to produce MSSQL code instead of SQLite code.
